# -*- coding: utf-8 -*-
"""20230831.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nro8fd838KwZ07jAPhWIQo4eKce3GoDs
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd


import io

file_name = list(uploaded.keys())[0]
file_content = uploaded[file_name]

df = pd.read_csv(io.BytesIO(file_content), encoding='shift_jis')

df.to_csv('my_data.csv', index=False)

!git clone https://github.com/iwatsuki23/plan10.git

# Commented out IPython magic to ensure Python compatibility.
# %cd plan10

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# 
# # タイトルの設定
# st.title('CSVデータの表示')
# 
# # CSVファイルの読み込み
# data = pd.read_csv('my_data.csv')
# st.write(data)
#











